version: '2'
services:
    jphone-app:
        image: jphone
        environment:
            - SPRING_PROFILES_ACTIVE=prod,swagger
            - SPRING_DATASOURCE_URL=jdbc:postgresql://jphone-postgresql:5432/jphone
            - JHIPSTER_SLEEP=10 # gives time for the database to boot before the application
        ports:
            - 8080:8080
    jphone-postgresql:
        extends:
            file: postgresql.yml
            service: jphone-postgresql
